name: Build & Publish VSCode Extension

on:
  push:
    tags:
      - '*'

jobs:
  publish_vsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun run build

      - name: Publish to VS Code Marketplace
        run: bunx vsce publish -p ${{ secrets.VSCE_TOKEN }}

  publish_ovsx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun run build

      - name: Publish to Open VSX
        run: bunx ovsx publish -p ${{ secrets.OPENVSX_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [publish_vsc, publish_ovsx]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun run build

      - name: Package extension
        run: bun run package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: |
            **Automated release for version ${{ github.ref_name }}**

            Built and published automatically via GitHub Actions.
          files: "*.vsix"