name: Build & Publish VSCode Extension

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF_NAME#v}
          echo "version=$TAG" >> $GITHUB_OUTPUT
          echo "Version from tag: $TAG"

      - name: Update package.json version
        run: |
          bunx json -I -f package.json -e "this.version='${{ steps.version.outputs.version }}'"

      - name: Build extension
        run: bun run build

      - name: Package extension
        run: bun run package

      - name: Publish to VS Code Marketplace
        run: bunx vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX
        run: bunx ovsx publish -p ${{ secrets.OPENVSX_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Automated release for version ${{ github.ref_name }}."
          files: "*.vsix"